# Generated by Django 3.2.2 on 2021-08-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_question_taker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='question',
        ),
    ]
